
#info: #定义各种额外的详情给服务端显示  
#  name: "@project.name@" #从pom.xml中获取  
#  description: "@project.description@"  
#  version: "@project.version@"  
#  spring-boot-version: "@project.parent.version@"

server:
  port: 8091

spring:
  application:
    name: SpringBoot客户端
  boot:
    admin:
      url: http://192.168.1.170:8080
      username: zteits
      password: zteits

management:
  security:
    enabled: false

logging:
  file: "target/spring-boot-admin-simple-client-demo.log"
